### PR TITLE
Added tests and changed some Closure type hints to callable

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by barryvdh** [comment]
Looks cool, but I can't merge it. Maybe update it to latest changes?

**Comment by hannesvdvreken** [comment]
Fixed it. Also provided a simple travis.yml file.

**Comment by barryvdh** [comment]
THanks

**Comment by barryvdh** [comment]
I've setup the webhooks :)
https://travis-ci.org/barryvdh/laravel-stack-middleware

**Comment by hannesvdvreken** [comment]
Awesome! Works right out of the box, even on hhvm.

**Pull request merged**
