### PR TITLE
	Remove middleware interfaces due to deprecation since Laravel 5.1

### PR DESCRIPTION
**Pull request by okaufmann**

### CODE REVIEW

**Comment by barryvdh** [comment]
Hmm, are they never used, also not in old version?
Otherwise bump to 5.1 minimum perhaps.

**Comment by okaufmann** [comment]
> Hmm, are they never used, also not in old version?

Sorry I don't understand your question. Can you give me more details?

**Comment by barryvdh** [comment]
I'm not sure if they ever checked for the middleware interface

**Comment by okaufmann** [comment]
I see! I just saw the notice in Laravel docs under http://laravel.com/docs/5.2/upgrade#upgrade-5.1.0 (Deprecations) says:

> The Illuminate\Contracts\Routing\Middleware contract has been deprecated. No contract is required on your middleware. In addition, the TerminableMiddleware contract has also been deprecated. Instead of implementing the interface, simply define a terminate method on your middleware.

After upgrading my first app to Laravel 5.2 i got an error saying that the interface was not found. That's the reason for this pull request.

**Comment by barryvdh** [comment]
Thanks

**Comment by okaufmann** [comment]
You're welcome!

**Comment by okaufmann** [comment]
Would i make sense to tag a new version? As seen from projects using Laravel 5.2 this is a bugfix.

**Comment by barryvdh** [comment]
Yeah its tagged now, `v0.2.2`

**Comment by okaufmann** [comment]
Thank's Barry !

**Pull request merged**
